### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object AlchemyCircle.Start () (at Assets/Scripts/AlchemyCircle.cs:42)

### ISSUE THREAD

**Issue by igame3dbill** [CiaccoDavide/Alchemy-Circles-Generator#3]
NullReferenceException: Object reference not set to an instance of an object
AlchemyCircle.Start () (at Assets/Scripts/AlchemyCircle.cs:42)

Like it says. Not sure what it wants from me.

Also  line 95 uses randomer.setSeed but the PRNG.cs uses plantSeed

**Comment by CiaccoDavide** [comment]
Hi, I just added the file "CiaccoRandom.cs" (the PRNG used by the alchemy circle generator)

https://github.com/CiaccoDavide/Alchemy-Circles-Generator/blob/master/src_Unity3D/CiaccoRandom.cs

Are you using the script on a RawImage?

Because it tries to access the RawImage component by default and rewrites its texture:

`ri = GetComponent<RawImage>();`
`[...]`
`ri.texture = texture;`

If you are using something else like a Sprite, UI.Image or Plane you will have to change the code accordingly!

Let me know if you need more help

**Comment by igame3dbill** [comment]
Okay now she's working, totally missed "Raw Image" in the menu, I shouldn't experiment so late.
